apiVersion: apps/v1
kind: Deployment
metadata:
  name: Pyhton-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Pyhton-app
  template:
    metadata:
      labels:
        app: Pyhton-app
    spec:
      containers:
      - name: Pyhton-app
        image: gokulraj8/finalapp:v43
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: Pyhton-app
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: Pyhton-app

